### ISSUE TITLE
Distance formula is wrong

### ISSUE THREAD

**Issue by jcaberio** [e-XpertSolutions/go-cluster#1]
https://github.com/e-XpertSolutions/go-cluster/blob/master/cluster/kprototypes.go#L276

should be 

`dist := km.Gamma*distCat + distNum` 

as stated in [Huang, Z. 1997](https://pdfs.semanticscholar.org/d42b/b5ad2d03be6d8fefa63d25d02c0711d19728.pdf)

>  γ  is a weight for categorical attributes for cluster l.

**Comment by mkuziora** [comment]
Yes, you are right. Thanks for pointing out this mistake. I will accept your pull request.
